# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smooth_n_cpp <- function(x, n) {
    .Call(`_PeakCorTest_smooth_n_cpp`, x, n)
}

rcpp_hello_world <- function() {
    .Call(`_PeakCorTest_rcpp_hello_world`)
}

